// <auto-generated />
using AristaEmployeeApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AristaEmployeeApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260617015300_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AristaEmployeeApp.Models.Cabang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerusahaanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerusahaanId");

                    b.ToTable("Cabangs");
                });

            modelBuilder.Entity("AristaEmployeeApp.Models.Karyawan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("CabangId")
                        .HasColumnType("int");

                    b.Property<string>("KodeKaryawan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerusahaanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CabangId");

                    b.HasIndex("PerusahaanId");

                    b.ToTable("Karyawans");
                });

            modelBuilder.Entity("AristaEmployeeApp.Models.Perusahaan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Perusahaans");
                });

            modelBuilder.Entity("AristaEmployeeApp.Models.Cabang", b =>
                {
                    b.HasOne("AristaEmployeeApp.Models.Perusahaan", "Perusahaan")
                        .WithMany("Cabangs")
                        .HasForeignKey("PerusahaanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perusahaan");
                });

            modelBuilder.Entity("AristaEmployeeApp.Models.Karyawan", b =>
                {
                    b.HasOne("AristaEmployeeApp.Models.Cabang", "Cabang")
                        .WithMany()
                        .HasForeignKey("CabangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AristaEmployeeApp.Models.Perusahaan", "Perusahaan")
                        .WithMany()
                        .HasForeignKey("PerusahaanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabang");

                    b.Navigation("Perusahaan");
                });

            modelBuilder.Entity("AristaEmployeeApp.Models.Perusahaan", b =>
                {
                    b.Navigation("Cabangs");
                });
#pragma warning restore 612, 618
        }
    }
}
