// <auto-generated />
using AristaEmployeeApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AristaEmployeeApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AristaEmployeeApp.Models.Cabang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NamaCabang");

                    b.Property<int>("PerusahaanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerusahaanId");

                    b.ToTable("Cabang");
                });

            modelBuilder.Entity("AristaEmployeeApp.Models.Karyawan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("CabangId")
                        .HasColumnType("int");

                    b.Property<string>("KodeKaryawan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NamaKaryawan");

                    b.Property<int>("PerusahaanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CabangId");

                    b.HasIndex("PerusahaanId");

                    b.ToTable("Karyawan");
                });

            modelBuilder.Entity("AristaEmployeeApp.Models.Perusahaan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NamaPerusahaan");

                    b.HasKey("Id");

                    b.ToTable("Perusahaan");
                });

            modelBuilder.Entity("AristaEmployeeApp.Models.Cabang", b =>
                {
                    b.HasOne("AristaEmployeeApp.Models.Perusahaan", "Perusahaan")
                        .WithMany()
                        .HasForeignKey("PerusahaanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perusahaan");
                });

            modelBuilder.Entity("AristaEmployeeApp.Models.Karyawan", b =>
                {
                    b.HasOne("AristaEmployeeApp.Models.Cabang", "Cabang")
                        .WithMany()
                        .HasForeignKey("CabangId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AristaEmployeeApp.Models.Perusahaan", "Perusahaan")
                        .WithMany()
                        .HasForeignKey("PerusahaanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cabang");

                    b.Navigation("Perusahaan");
                });
#pragma warning restore 612, 618
        }
    }
}
